name: cheppers-feladat
recipe: drupal9
config:
  webroot: web/

services:
    # DATABASE: Mysql server
    database:
      creds:
        user: drupal9
        password: drupal9
        database: drupal9
